baseURL = 'https://yuvraj2987.github.io/'
languageCode = 'en-us'
title = 'Amit Kulkarni'
theme = 'hugo-coder'
publishDir = "docs"

pagination = 20


[markup.highlight]
style = "github-dark"

[params]
  author = "Amit Kulkarni"
  info = "Software Reliability Engineer"
  description = "Amit Kulkarni's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "experimentalistforlife+web@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2012

  # enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/yuvraj2987"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "Resume"
  weight = 2
  url = "resume/"
 